### ISSUE TITLE
<formula_data> missing definitions 

### ISSUE THREAD

**Issue by agomezl** [DanielSchuessler/logic-TPTP#1]
I was trying to parse this formula

```
cnf(refute_0_9, plain, (hates(butler, X_8) | richer(X_8, agatha)),
    inference(subst, [], [refute_0_8 : [bind(X, $fot(X_8))]])).
```

And get this error

```
tstp2agda: Parse error, pos: [RP,RP,Rbrack,Rbrack,RP,RP,Dot]
```

After some digging, I found that the error is related with `$fot(X_8)` and the
way `<formula_data>` is defined in `Parser.y`

```
formula_data :: {GData}
formula_data  : dollar_word lp fof_formula  rp { GFormulaData $1 $3 }
              -- too ambiguous | dollar_word lp cnf_formula  rp { GFormulaData $1 $3 }
```

Which differs with the one in the TPTP syntax

```
<formula_data> ::= $thf(<thf_formula>) | $tff(<tff_formula>) |
                   $fof(<fof_formula>) | $cnf(<cnf_formula>) |
                   $fot(<term>)
```

I guess this could be fixed with something like

```
%token
 ...
 -- Some new tokens
 tok_fd_fof             { DollarWord "$fot" }
 tok_fd_cnf             { DollarWord "$cnf" }
 ...
%%
...
-- A somehow better definition for <formula_data>
formula_data :: {GData}
formula_data  :  tok_fd_fof lp fof_formula  rp { GFormulaData "$fof" $3 }
               | tok_fd_cnf lp cnf_formula  rp { GFormulaData "$cnf" $3 }
```

But this still left out the case with `$fot(<term>)` since this may need an
extra data constructor for `GData`  thus not actually fixing the problem.
what do you think is the proper  way to solve this issue?

Thanks.

**Comment by msakai** [comment]
Hi @agomezl,
I recently became a maintainer of logic-TPTP and released version 0.5.0.0 which includes your fix for the problem.
Thanks for making the issue and the pull request.
