### ISSUE TITLE
Missing required versions of Alex and Happy

### ISSUE THREAD

**Issue by asr** [DanielSchuessler/logic-TPTP#7]
I got some compilation errors building the library using old versions of Alex and Happy (3.0.5 and 1.18.10, respectively). I fixed the problem using the latest versions of these programs (Alex 3.2.2 and Happy 1.19.6). Please add lower bounds for these programs.

**Comment by DanielSchuessler** [comment]
Added lower bounds according to the lowest Alex and Happy versions that I could check quickly (alex-3.1.1, happy-1.19.1). If it works with even older versions and someone wants to compile with these, I can lower the bounds.

**Comment by asr** [comment]
Thanks for fixing the issue so fast!
